3 get topics
alicjafleszar/be-nc-news pull request #1
Opened 2023-05-09 15:02 UTC by alicjafleszar

2023-05-09 15:20 UTC, B7Bprog requested changes
Hey Alicja, please see my comments, refactor your code, then it's good to merge. 👍

2023-05-09 15:20 UTC, B7Bprog commented on app.js
> +app.use((req, res, next) => {
Here as a first parameter you could add '*' to catch all invalid paths. 

An even better way is to use app.all(). (app.all('*', ()=>{}).

2023-05-09 15:20 UTC, B7Bprog commented on __tests__/app.test.js
> +                .then(({ body: { topics } }) => {
Nice nested destructuring here.

2023-05-09 15:20 UTC, B7Bprog commented on __tests__/app.test.js
> +                    topics.forEach(topic => {
This is all good, but for the future I recommend the use of the following flexible object matchers:

.toMatchObject
.objectContaining

2023-05-10 08:59 UTC, Rayhaan2k9 approved these changes
Well done Alicja! Merge away 😁

2023-05-10 09:28 UTC, closed without merging